typography_spectrum: 0.17620668816380203
color:
  brandStrength: 0.982714960584417
  lightness: 0.3420770834200084
  saturation: 0.8201016958337277
  rhythmicContrast: 0.47686447435989976
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.7947512404061854
name: 'We are our Time. If we are good, the Times are good'
navigation:
  - name: The Mission
    url: thegrid.ai/integreator/mission
    type: external
title: integreator
description: smart pure clear
